version: '3.3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - './prometheus:/etc/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
     # Uncomment to expose the prometheus web UI to the host.
#    ports:
#      - '9090:9090'
  node-exporter:
    image: prom/node-exporter:latest

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  teku:
    image: pegasyseng/teku:develop
    environment:
      - 'JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data -Xmx1200m'
      - TEKU_NETWORK=schlesi
      - 'TEKU_P2P_STATIC_PEERS=/ip4/54.147.29.135/tcp/9546/p2p/16Uiu2HAmVUBYqki8u6vuz56fqfxRS3RLzLriMtr7akkWKwcv9Xwg'
      - TEKU_REST_API_ENABLED=true
      - TEKU_METRICS_ENABLED=true
      - 'TEKU_METRICS_INTERFACE=0.0.0.0'
      - TEKU_METRICS_PORT=8008
      - 'TEKU_METRICS_HOST_WHITELIST=*'
      - TEKU_ETH1_ENABLED=true
      - 'TEKU_ETH1_ENDPOINT=http://host.docker.internal:8545'
      - TEKU_DATA_PATH=/data/teku
      - TEKU_LOG_FILE=/data/teku.log
      - TEKU_VALIDATORS_KEY_FILES="/data/keys/validator_846af35/validator_846af35.json"
      - TEKU_VALIDATORS_KEY_PASSWORD_FILES="/data/keys/validator_846af35/password.txt"
    volumes:
      - './teku:/data'
    ports:
      - "9000:9000"
      - "5051:5051"
      - "8008:8008"